"""Tier 1.1 manipulation skill — top-level API.

Single entry-point that Tier 2 Skill Dispatcher calls:

    trajectory, events = manip_skill(
        vad=np.array([V, A, D]),         # ∈ [-1, +1]^3
        object_pose=SE3,                  # 6-DoF object world pose
        recipient_pose=SE3,               # 6-DoF recipient face/chest pose
        action_class="give",              # {give, present, offer}
    )

Internally the skill decomposes the request into an autoregressive sequence of
~1-second motion primitives (approach → grasp → lift → transport → present →
release → retreat), each generated by a single shared FlowDART-HOI backbone
under VAD classifier guidance.  Object motion is derived from wrist motion
after the grasp event; grasp pose comes from a pre-computed AnyGrasp lookup.

This module is intentionally a stub at creation time.  Concrete
implementations land in sibling modules:

    primitives.py           7-primitive vocabulary + sequencer (TBD)
    model/denoiser_hoi.py   FlowDART-HOI denoiser (TBD)
    flow_matching/sampler.py FM sampler with classifier guidance (TBD)
    data/handoversim.py     HandoverSim / GRAB primitive slicing (TBD)
    grasp/lookup.py         AnyGrasp pre-compute per object (TBD)
    train/primitive_g1.py   trainer (TBD)
    render/playback.py      MuJoCo / Blender render (TBD)
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import numpy as np


ActionClass = Literal["give", "present", "offer"]


@dataclass
class ManipOutput:
    """Result of one manipulation skill call.

    trajectory  : (T, 43) — 29 body DOF + 14 hand DOF, float32, 30 Hz
    grasp_close : timestamp (seconds) at which fingers close on object
    grasp_open  : timestamp (seconds) at which fingers release object
    primitive_log : list of (primitive_name, start_frame, end_frame) for debug
    """
    trajectory: np.ndarray
    grasp_close: float
    grasp_open: float
    primitive_log: list[tuple[str, int, int]]


def manip_skill(
    vad: np.ndarray,
    object_pose: np.ndarray,
    recipient_pose: np.ndarray,
    action_class: ActionClass = "give",
) -> ManipOutput:
    """Generate a VAD-styled grasp + handover trajectory on G1.

    Parameters
    ----------
    vad : (3,) float32 in [-1, +1]
        Target valence-arousal-dominance code.
    object_pose : (4, 4) or (7,) SE(3)
        Object world pose (initial state).
    recipient_pose : (4, 4) or (7,) SE(3)
        Recipient face/chest world pose.
    action_class : {"give", "present", "offer"}
        High-level interaction class from Tier 2 dispatcher.

    Returns
    -------
    ManipOutput
    """
    raise NotImplementedError(
        "ManipAgent skill is a stub.  See docs/notes/architecture/manip_goal.md "
        "for the full design contract; sibling modules will fill this in."
    )
