"""Architecture C — Inpainting Flow Matching sampler.

Same Euler / Heun / RK4 ODE as FMSampler, plus a hard inpainting overwrite
at every step (and inside q_sample for training):
    x = obs_x0 * obs_mask + x * (1 - obs_mask)

This guarantees the observed (history) region is byte-identical to the GT
context — eliminating primitive-seam jumps by construction.

Lifted from `MoGenAgent.flow_matching.sampler.FMSampler` and extended; kept as a
separate file so the existing 35 / 63 / 65-dim non-inpainting code paths are
unaffected.
"""
from __future__ import annotations
from typing import Callable, Optional

import torch


# Same convention as fm_sampler.py — discretize continuous t ∈ [0, 1] to an
# integer bin used by the existing TimestepEmbedder.
NUM_T_BINS = 1000


def _continuous_to_discrete_t(t: torch.Tensor) -> torch.Tensor:
    return (t * (NUM_T_BINS - 1)).round().clamp(0, NUM_T_BINS - 1).long()


class FMSamplerInpaint:
    """Inpainting-aware Flow Matching forward / reverse operations."""

    def __init__(self, num_t_bins: int = NUM_T_BINS, t_eps: float = 1e-3,
                 t_sampling: str = 'uniform', logit_normal_mean: float = 0.0,
                 logit_normal_std: float = 1.0,
                 parameterization: str = 'x0',
                 sigma_min: float = 0.0):
        self.num_t_bins = num_t_bins
        self.t_eps = t_eps
        self.t_sampling = t_sampling
        self.logit_normal_mean = logit_normal_mean
        self.logit_normal_std = logit_normal_std
        assert parameterization in ('x0', 'v'), f"unknown parameterization: {parameterization}"
        self.parameterization = parameterization
        self.sigma_min = sigma_min

    # ── Training: forward process ──────────────────────────────────────────

    def sample_t(self, batch_size: int, device, dtype=torch.float32) -> torch.Tensor:
        """Same as FMSampler.sample_t."""
        if self.t_sampling == 'logit_normal':
            z = torch.randn(batch_size, device=device, dtype=dtype) * self.logit_normal_std + self.logit_normal_mean
            t = torch.sigmoid(z)
        else:
            u = torch.rand(batch_size, device=device, dtype=dtype)
            t = self.t_eps + u * (1.0 - 2 * self.t_eps)
        return t.clamp(self.t_eps, 1.0 - self.t_eps)

    def q_sample(self, x0: torch.Tensor, t: torch.Tensor,
                 noise: Optional[torch.Tensor] = None,
                 obs_mask: Optional[torch.Tensor] = None) -> torch.Tensor:
        """Linear interpolation forward process with inpainting.

        Standard FM: x_t = (1 - t) * noise + t * x0
        With inpaint: observed positions stay clean (no noise added).

            x_t = obs_mask * x0 + (1 - obs_mask) * [(1 - t) * noise + t * x0]

        Args:
            x0: clean data, shape (B, T, D)
            t: timestep ∈ [0, 1], shape (B,)
            noise: optional precomputed noise, same shape as x0
            obs_mask: optional (B, T, D) — observed positions stay clean.

        Returns:
            x_t: noisy interpolation, same shape as x0
        """
        if noise is None:
            noise = torch.randn_like(x0)
        t_b = t.view(-1, *([1] * (x0.dim() - 1)))
        if self.sigma_min > 0:
            x_t = (1.0 - (1.0 - self.sigma_min) * t_b) * noise + t_b * x0
        else:
            x_t = (1.0 - t_b) * noise + t_b * x0
        if obs_mask is not None:
            x_t = obs_mask * x0 + (1.0 - obs_mask) * x_t
        return x_t

    # ── Inference: reverse process (Euler / Heun / RK4 ODE) ────────────────

    @torch.no_grad()
    def sample(self,
               model: Callable,
               shape: tuple,
               device,
               num_steps: int = 1,
               cfg_scale: float = 1.0,
               y: Optional[dict] = None,
               obs_x0: Optional[torch.Tensor] = None,
               obs_mask: Optional[torch.Tensor] = None,
               noise: Optional[torch.Tensor] = None,
               progress: bool = False,
               solver: str = 'euler',
               rewriting_mode: str = 'hard',
               rewriting_stop_t: float = 0.2) -> torch.Tensor:
        """Generate samples via ODE integration with inpainting / rewriting.

        Three modes for the observed (history) region:

        - rewriting_mode='hard' (default, original behavior):
            x[obs] = obs_x0 every step. Init: x = obs_x0*mask + noise*(1-mask).
            Guarantees byte-identical history; but creates clean/noisy inhomogeneity
            in the input sequence at every step.

        - rewriting_mode='soft' (MFM-style trajectory rewriting, arxiv 2312.08895):
            For t < rewriting_stop_t, x[obs] = (1-t)*noise + t*obs_x0 (the linear
            FM trajectory from noise to GT). For t >= rewriting_stop_t, no overwrite —
            history is regenerated by the model. Init: x = noise everywhere.
            Eliminates the clean/noisy gap and lets future and history co-evolve.

        - rewriting_mode='none':
            No overwrite at all (treat inpaint model as vanilla FM). For ablation.

        Args mirror FMSampler.sample with the addition of obs_x0 / obs_mask /
        rewriting_mode / rewriting_stop_t.
        """
        B = shape[0]
        if noise is None:
            noise = torch.randn(*shape, device=device)
        # Keep noise around for soft rewriting (needs original noise at every step)
        noise_init = noise

        if rewriting_mode == 'hard' and obs_x0 is not None and obs_mask is not None:
            x = obs_x0 * obs_mask + noise_init * (1.0 - obs_mask)
        else:
            # soft / none: start from pure noise everywhere
            x = noise_init.clone()

        dt = 1.0 / num_steps

        def _v_at(x_in, t_scalar):
            t = torch.full((B,), t_scalar, device=device, dtype=torch.float32)
            t_int = _continuous_to_discrete_t(t)
            model_out = self._forward_with_cfg(model, x_in, t_int, y,
                                                cfg_scale, obs_x0, obs_mask)
            if self.parameterization == 'v':
                return model_out
            denom = max(1.0 - t_scalar, self.t_eps)
            return (model_out - x_in) / denom

        def _overwrite(x_curr, t_scalar=0.0):
            if obs_x0 is None or obs_mask is None:
                return x_curr
            if rewriting_mode == 'hard':
                return obs_x0 * obs_mask + x_curr * (1.0 - obs_mask)
            elif rewriting_mode == 'soft':
                if t_scalar < rewriting_stop_t:
                    target = (1.0 - t_scalar) * noise_init + t_scalar * obs_x0
                    return obs_mask * target + (1.0 - obs_mask) * x_curr
                return x_curr
            elif rewriting_mode == 'none':
                return x_curr
            else:
                raise ValueError(f"Unknown rewriting_mode: {rewriting_mode}")

        for k in range(num_steps):
            t_scalar = k * dt

            if solver == 'euler':
                v = _v_at(x, t_scalar)
                x = x + dt * v

            elif solver == 'heun':
                k1 = _v_at(x, t_scalar)
                x_pred = x + dt * k1
                if t_scalar + dt >= 1.0 - self.t_eps:
                    x = x_pred
                else:
                    x_pred = _overwrite(x_pred, t_scalar + dt)
                    k2 = _v_at(x_pred, t_scalar + dt)
                    x = x + dt * 0.5 * (k1 + k2)

            elif solver == 'rk4':
                if t_scalar + dt >= 1.0 - self.t_eps:
                    k1 = _v_at(x, t_scalar)
                    x = x + dt * k1
                else:
                    k1 = _v_at(x, t_scalar)
                    k2 = _v_at(_overwrite(x + 0.5 * dt * k1, t_scalar + 0.5 * dt), t_scalar + 0.5 * dt)
                    k3 = _v_at(_overwrite(x + 0.5 * dt * k2, t_scalar + 0.5 * dt), t_scalar + 0.5 * dt)
                    k4 = _v_at(_overwrite(x + dt * k3,       t_scalar + dt),       t_scalar + dt)
                    x = x + dt * (k1 + 2 * k2 + 2 * k3 + k4) / 6.0

            else:
                raise ValueError(f"Unknown solver: {solver}. Use 'euler', 'heun', or 'rk4'.")

            # Apply mode-specific overwrite (hard always, soft only if t < stop_t, none never).
            x = _overwrite(x, t_scalar + dt)

            if progress:
                print(f"  FM-inpaint step {k+1}/{num_steps}: t={t_scalar:.3f} solver={solver}")

        return x

    @torch.no_grad()
    def sample_single_step(self,
                            model: Callable,
                            shape: tuple,
                            device,
                            cfg_scale: float = 1.0,
                            y: Optional[dict] = None,
                            obs_x0: Optional[torch.Tensor] = None,
                            obs_mask: Optional[torch.Tensor] = None,
                            noise: Optional[torch.Tensor] = None) -> torch.Tensor:
        """One-shot prediction: x0 = model(noise + obs_inpaint, t=0)."""
        B = shape[0]
        if noise is None:
            noise = torch.randn(*shape, device=device)
        if obs_x0 is not None and obs_mask is not None:
            x = obs_x0 * obs_mask + noise * (1.0 - obs_mask)
        else:
            x = noise
        t = torch.zeros(B, device=device, dtype=torch.float32)
        t_int = _continuous_to_discrete_t(t)
        out = self._forward_with_cfg(model, x, t_int, y, cfg_scale,
                                       obs_x0, obs_mask)
        if obs_x0 is not None and obs_mask is not None:
            out = obs_x0 * obs_mask + out * (1.0 - obs_mask)
        return out

    # ── CFG helper ─────────────────────────────────────────────────────────

    def _forward_with_cfg(self, model, x, t_int, y, cfg_scale,
                           obs_x0=None, obs_mask=None):
        """Run model forward with classifier-free guidance.

        Same convention as FMSampler._forward_with_cfg: y['uncond'] = True
        forces unconditional. obs_x0 / obs_mask are kept the SAME on both
        branches (we want to amplify the text axis only — not drop the
        history; history is GT, not a condition we guide away from).
        """
        if cfg_scale == 1.0 or y is None:
            return model(x_t=x, timesteps=t_int, y=y,
                         obs_x0=obs_x0, obs_mask=obs_mask)
        y_cond = dict(y);   y_cond['uncond'] = False
        out_cond = model(x_t=x, timesteps=t_int, y=y_cond,
                          obs_x0=obs_x0, obs_mask=obs_mask)
        y_uncond = dict(y); y_uncond['uncond'] = True
        out_uncond = model(x_t=x, timesteps=t_int, y=y_uncond,
                            obs_x0=obs_x0, obs_mask=obs_mask)
        return out_uncond + cfg_scale * (out_cond - out_uncond)
