"""Render top-1 exemplar MP4 per motion_lib primitive.

For each primitive in configs/motion_lib.yaml, render its first exemplar:
  - BABEL source: data/G1_Filtered_DATA/babel_npz/<seq>.npz
                  (quat xyzw → wxyz swap required, see audit_vad_babel_segment.py)
  - BONES fallback (currently only `thumbs_up` → `bravo_R_001`):
                  data/G1_Filtered_DATA/BONES_filtered/successful/
                  (quat already wxyz, no swap; 50fps → downsample to 30fps render)

Output:
  data/motion_lib/<family>/<name>/<name>.mp4

This script reads ONLY numeric fields from NPZ — works with DART env's
numpy 1.24.4 (which can't read object-dtype `segment_labels` from BABEL).
Segment start/end frames come from data/motion_lib/exemplar_scan.yaml
(generated by find_motion_lib_exemplars.py via system python).
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

os.environ.setdefault('MUJOCO_GL', 'egl')
os.environ.setdefault('PYTHONNOUSERSITE', '1')

import numpy as np
import yaml
import imageio
import mujoco as mj

DART_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(DART_ROOT / 'src'))
from MoGenAgent.utils.g1_utils import G1_XML_PATH

LIB_YAML  = DART_ROOT / 'configs/VAD/motion_lib.yaml'
SCAN_YAML = DART_ROOT / 'data/motion_lib/exemplar_scan.yaml'
BABEL_DIR = DART_ROOT / 'data/G1_Filtered_DATA/babel_npz'
BONES_DIR = DART_ROOT / 'data/G1_Filtered_DATA/BONES_filtered/successful'
OUT_ROOT  = DART_ROOT / 'data/motion_lib'

VIDEO_W, VIDEO_H, VIDEO_FPS = 480, 360, 30

# Camera angle relative to actor's FACING direction (degrees).
# -45 = front-right 3/4 view (cinematic, matches build_perceptual_bench.py).
CAM_AZIMUTH_OFFSET = float(os.environ.get('CAM_AZIMUTH_OFFSET', '-45'))


def yaw_from_quat_wxyz(q: np.ndarray) -> float:
    w, x, y, z = float(q[0]), float(q[1]), float(q[2]), float(q[3])
    yaw_rad = np.arctan2(2.0 * (w * z + x * y), 1.0 - 2.0 * (y * y + z * z))
    return float(np.degrees(yaw_rad))


def actor_facing_yaw_deg(q_wxyz: np.ndarray) -> float:
    """Actor's GAZE direction in world frame (degrees). +180° because G1/SMPL
    retarget has actor facing world -X at root_quat=identity."""
    return yaw_from_quat_wxyz(q_wxyz) + 180.0

# BONES fallback for primitives BABEL doesn't cover.
# Value = (npz_filename_without_ext, start_frame_50fps, end_frame_50fps)
# end=None → render whole clip.
BONES_FALLBACK = {
    'thumbs_up': ('bravo_R_001__A428', 0, None),
}


def quat_xyzw_to_wxyz(q: np.ndarray) -> np.ndarray:
    return np.concatenate([q[..., 3:4], q[..., :3]], axis=-1)


def render_motion(rp: np.ndarray, rq_wxyz: np.ndarray, dof: np.ndarray,
                  fps: float, out_path: Path,
                  model: mj.MjModel, renderer: mj.Renderer, cam: mj.MjvCamera) -> int:
    """Render qpos sequence to MP4. Returns # frames written."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    pelvis_id = model.body('pelvis').id
    data = mj.MjData(model)
    # Align cam.azimuth to actor's facing direction — every primitive shows same view.
    cam.azimuth = actor_facing_yaw_deg(rq_wxyz[0]) + CAM_AZIMUTH_OFFSET
    step = max(1, int(round(fps / VIDEO_FPS)))
    writer = imageio.get_writer(str(out_path), fps=VIDEO_FPS, codec='libx264',
                                 quality=8, macro_block_size=1)
    n = 0
    try:
        for t in range(0, len(rp), step):
            data.qpos[:3] = rp[t]
            data.qpos[3:7] = rq_wxyz[t]
            data.qpos[7:36] = dof[t]
            mj.mj_forward(model, data)
            cam.lookat[:] = data.xpos[pelvis_id]
            renderer.update_scene(data, camera=cam)
            writer.append_data(renderer.render())
            n += 1
    finally:
        writer.close()
    return n


def render_babel(primitive: str, family: str, exemplar: dict,
                 model, renderer, cam) -> tuple[Path, str]:
    """Render BABEL segment. exemplar has {seq, seg, start, end, sec, label}."""
    seq = exemplar['seq']
    start = int(exemplar['start'])
    end = int(exemplar['end'])
    npz_p = BABEL_DIR / f'{seq}.npz'
    if not npz_p.exists():
        raise FileNotFoundError(f'BABEL NPZ missing: {npz_p}')
    d = np.load(npz_p, allow_pickle=True)
    rp = d['root_pos'].astype(np.float32)
    rq_xyzw = d['root_quat'].astype(np.float32)   # actually xyzw in BABEL
    dof = d['dof_pos'].astype(np.float32)
    fps = float(d['fps'])
    rq_wxyz = quat_xyzw_to_wxyz(rq_xyzw)

    # Slice segment
    end = min(end, len(rp))
    start = max(0, min(start, end - 2))
    rp = rp[start:end]; rq_wxyz = rq_wxyz[start:end]; dof = dof[start:end]

    out_path = OUT_ROOT / family / primitive / f'{primitive}.mp4'
    n = render_motion(rp, rq_wxyz, dof, fps, out_path, model, renderer, cam)
    return out_path, f'BABEL {seq}__seg{exemplar["seg"]} [{start}:{end}] @{fps}fps → {n} frames'


def render_bones(primitive: str, family: str,
                 model, renderer, cam) -> tuple[Path, str]:
    """Render BONES fallback. Uses BONES_FALLBACK entry."""
    npz_stem, start, end = BONES_FALLBACK[primitive]
    npz_p = BONES_DIR / f'{npz_stem}.npz'
    if not npz_p.exists():
        raise FileNotFoundError(f'BONES NPZ missing: {npz_p}')
    d = np.load(npz_p, allow_pickle=True)
    rp = d['sim_root_pos'].astype(np.float32)
    rq_wxyz = d['sim_root_quat'].astype(np.float32)   # BONES is wxyz already
    dof = d['sim_dof_pos'].astype(np.float32)
    fps = float(d.get('fps', 50.0))

    if end is None:
        end = len(rp)
    end = min(end, len(rp))
    start = max(0, min(start, end - 2))
    rp = rp[start:end]; rq_wxyz = rq_wxyz[start:end]; dof = dof[start:end]

    out_path = OUT_ROOT / family / primitive / f'{primitive}.mp4'
    n = render_motion(rp, rq_wxyz, dof, fps, out_path, model, renderer, cam)
    return out_path, f'BONES {npz_stem} [{start}:{end}] @{fps:.0f}fps → {n} frames'


def main():
    print(f'[load] {LIB_YAML.relative_to(DART_ROOT)} + {SCAN_YAML.relative_to(DART_ROOT)}')
    with open(LIB_YAML) as f:
        lib = yaml.safe_load(f)
    with open(SCAN_YAML) as f:
        scan = yaml.safe_load(f)

    # Build flat (primitive, family, top_exemplar_with_start_end) list
    tasks: list[tuple[str, str, dict | None]] = []
    for family in ('gesture', 'locomotion'):
        for p in lib[family]:
            name = p['name']
            scan_entries = scan['exemplars'].get(name, [])
            top_exemplar = scan_entries[0] if scan_entries else None
            tasks.append((name, family, top_exemplar))

    print(f'\n[render] {len(tasks)} primitives, output → {OUT_ROOT.relative_to(DART_ROOT)}/<family>/<name>/<name>.mp4')

    print(f'[mujoco] init renderer (W={VIDEO_W} H={VIDEO_H} fps={VIDEO_FPS})...')
    model = mj.MjModel.from_xml_path(str(G1_XML_PATH))
    renderer = mj.Renderer(model, height=VIDEO_H, width=VIDEO_W)
    cam = mj.MjvCamera()
    cam.distance, cam.elevation = 3.0, -10  # azimuth set per-clip by render_motion()

    ok, fail = 0, 0
    for name, family, top_ex in tasks:
        try:
            if top_ex is None:
                # No BABEL match — try BONES fallback
                if name in BONES_FALLBACK:
                    out_path, info = render_bones(name, family, model, renderer, cam)
                    print(f'  ✓ {name:14s}  {info}  →  {out_path.relative_to(DART_ROOT)}')
                    ok += 1
                else:
                    print(f'  ⚠ {name:14s}  no BABEL exemplar AND no BONES_FALLBACK entry — skipping')
                    fail += 1
                continue
            out_path, info = render_babel(name, family, top_ex, model, renderer, cam)
            print(f'  ✓ {name:14s}  {info}  →  {out_path.relative_to(DART_ROOT)}')
            ok += 1
        except Exception as e:
            print(f'  ✗ {name:14s}  ERR {type(e).__name__}: {e}')
            fail += 1

    print(f'\n[done] {ok} rendered / {fail} skipped')


if __name__ == '__main__':
    main()
